version: '3.8'

services:
  # 远程镜像版本 - 当GitHub Actions构建完成后使用
  xielin:
    image: ghcr.io/linon419/xielin:latest
    container_name: xielin-app
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      # CCXT私有API配置
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET=${BINANCE_SECRET}
      - OKEX_API_KEY=${OKEX_API_KEY}
      - OKEX_SECRET=${OKEX_SECRET}
      - OKEX_PASSPHRASE=${OKEX_PASSPHRASE}
      - BYBIT_API_KEY=${BYBIT_API_KEY}
      - BYBIT_SECRET=${BYBIT_SECRET}
    volumes:
      - ./data:/app/data
      - ./logs:/var/log/supervisor
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health", "&&", "curl", "-f", "http://localhost/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  xielin-data:
    driver: local
