version: '3.8'

# 开发环境 Docker Compose 配置
# 使用方法: docker-compose -f docker-compose.dev.yml up --build

services:
  # 合并的前后端服务 - 开发模式
  xielin-dev:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    container_name: xielin-app-dev
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DEBUG=true
    volumes:
      - ./data:/app/data
      - ./logs:/var/log/supervisor
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health", "&&", "curl", "-f", "http://localhost/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  xielin-data:
    driver: local
